type: "history"
model: "Qwen/Qwen3-8B"
compressor_type: "full"
prompts:
  prompt_system: "system_prompt"
  prompt_history_user: "prompt_history_v2"
# TODO: The threshold is set manually!
history_summarization_threshold: 4096
preserve_last_k_turns: 1
history_summary_rule: "reset"